import { GroupBox, HorizontalBox, VerticalBox, Button, ProgressIndicator, LineEdit, Palette } from "std-widgets.slint";
import "../CaskaydiaCove-Regular.ttf";

export component MainWindow inherits Window {
    pure callback render_plot() -> image;
    pure callback tcp_server(string, int);
    
    out property <string> appid;
    out property <string> server_ip;
    out property <int> listen_port;
    in property <int> plot_process;

    title: "Im a Plotter";
    min-width: 800px;
    default-font-family: "Caskaydia Cove";
    default-font-size: 15px;
    min-height: 600px;

    VerticalBox {
        alignment: LayoutAlignment.space-between;
        HorizontalBox {
            alignment: LayoutAlignment.space-around;
            spacing: 30px;
            padding: 10px;
            Text {
                font-size: 18px; 
                text: "Server IP";
                vertical-alignment: TextVerticalAlignment.center;
            }
            
            LineEdit {
                input-type: text;
                placeholder-text: "127.0.0.1";
                width: 300px;
                text: root.server_ip;
                edited(text) => {
                    root.server_ip = text;
                }
            }
        
            Text {
                font-size: 18px;
                text: "Port";
                vertical-alignment: TextVerticalAlignment.center;
            }

            LineEdit {
                input-type: number;
                placeholder-text: "2887";
                width: 80px;
                text: root.listen_port;
                edited(text) => {
                    root.listen_port = text.to-float();
                }
            }
            
            Button {
                text: "Listen";
                checkable: true;
                clicked => {
                    root.tcp_server(server_ip, listen_port);
                }
            }
        }
        Image {
            width: 80%;
            image-fit: contain;
            source: root.render_plot();
            accessible-label: "Loading....";
        }
        ProgressIndicator {
            width: 80%;
            height: 1%;
            progress: plot_process;
        }
    }
}
