name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env: 
      SLINT_STYLE: fluent-dark
    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt update -y && sudo apt install -y fontconfig libfontconfig1-dev
        fi
    - name: Build
      id: build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: tcp_plotter
        path: |
          "target/release/tcp_plotter"
          "target/release/tcp_plotter.exe"
          
