name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env: SLINT_STYLE=fluent-dark
    
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt update -y && sudo apt install -y fontconfig libfontconfig1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: tcp_plotter
        path: target/${{ matrix.BUILD_TARGET }}/tcp_plotter
